const NARRATION_LABELS = ['Concise', 'Balanced', 'Detailed', 'Over-narrated'];
const BLUNTNESS_LABELS = ['Soft', 'Balanced', 'Direct', 'Blunt'];
const INITIATIVE_LABELS = ['Passive', 'Reactive', 'Proactive', 'Leading'];
const EMOTION_LABELS = ['Muted', 'Balanced', 'Expressive', 'Intense'];

export function sliderLabel(key, value) {
  const map = {
    narration: NARRATION_LABELS,
    bluntness: BLUNTNESS_LABELS,
    initiative: INITIATIVE_LABELS,
    emotion: EMOTION_LABELS
  };
  return (map[key] || [])[value] || 'Balanced';
}

function buildBehaviorBlock(char) {
  const parts = [];

  parts.push(`Narration level: ${NARRATION_LABELS[char.narration] || 'Balanced'}.`);
  parts.push(`Tone: ${BLUNTNESS_LABELS[char.bluntness] || 'Balanced'}.`);
  parts.push(`Initiative: ${INITIATIVE_LABELS[char.initiative] || 'Reactive'}.`);
  parts.push(`Emotion: ${EMOTION_LABELS[char.emotion] || 'Balanced'}.`);

  const rules = [];
  if (char.avoidCliches) {
    rules.push('Avoid clichés, generic reassurance, tired idioms, and overused romance tropes.');
  }
  if (char.avoidLoops) {
    rules.push('Do not end every message with a question. Let silence and statements breathe.');
  }
  if (char.stayInCharacter) {
    rules.push('Stay in character at all times. Do not narrate as an AI, summarize the scene, or break the fourth wall.');
  }
  if (char.overNarrate) {
    rules.push('Over-narrate sensory and emotional details, but keep them grounded and specific.');
  }

  if (rules.length) {
    parts.push('Rules: ' + rules.join(' '));
  }

  return parts.join(' ');
}

export function buildMarkdown(char) {
  const sections = [];

  const nameLine = char.name ? `You are ${char.name}` : 'You are a character';
  const roleLine = char.role ? `, acting as ${char.role}.` : '.';
  sections.push(`# Identity\n\n${nameLine}${roleLine}`);

  if (char.appearance) {
    sections.push(`# Appearance\n\n${char.appearance}`);
  }
  if (char.personality) {
    sections.push(`# Personality\n\n${char.personality}`);
  }
  if (char.background) {
    sections.push(`# Background / scenario\n\n${char.background}`);
  }
  if (char.speech) {
    sections.push(`# Speaking style\n\n${char.speech}`);
  }
  if (char.examples) {
    sections.push(`# Example dialogue\n\n${char.examples}`);
  }

  sections.push(`# Behavior\n\n${buildBehaviorBlock(char)}`);

  if (char.extra) {
    sections.push(`# Additional instructions\n\n${char.extra}`);
  }

  sections.push(
    `# Output instructions\n\n` +
    `- Respond in character. Do not break the fourth wall.\n` +
    `- Be natural, not performative. Specifics beat theatrical declarations.\n` +
    `- If the user gives little context, advance the scene rather than repeating questions.`
  );

  return sections.join('\n\n---\n\n');
}

export function buildLmStudioJson(char) {
  const systemPrompt = buildMarkdown(char);
  return JSON.stringify({
    name: char.name || 'Character',
    description: `A ${char.role || 'character'} preset generated by Prompt Forge`,
    system_prompt: systemPrompt,
    user_message_prefix: '',
    user_message_suffix: '',
    assistant_message_prefix: '',
    assistant_message_suffix: '',
    preprompt: systemPrompt
  }, null, 2);
}

export function buildSillyTavernJson(char) {
  return JSON.stringify({
    name: char.name || 'Character',
    description: `A ${char.role || 'character'} preset generated by Prompt Forge`,
    personality: char.personality || '',
    scenario: char.background || '',
    first_mes: '',
    mes_example: char.examples || '',
    creatorcomment: '',
    tags: ['prompt-forge', char.role || 'character'].filter(Boolean),
    creator: 'Prompt Forge',
    character_version: '1.0',
    alternate_greetings: [],
    system_prompt: buildMarkdown(char),
    post_history_instructions: char.extra || '',
    appearance: char.appearance || '',
    personality_summary: char.personality || ''
  }, null, 2);
}

export function buildCharacterOutput(char) {
  switch (char.format) {
    case 'lmstudio':
      return buildLmStudioJson(char);
    case 'sillytavern':
      return buildSillyTavernJson(char);
    case 'markdown':
    default:
      return buildMarkdown(char);
  }
}
